2023-12-03 18:33:32,732 INFO    MainThread:36808 [wandb_setup.py:_flush():76] Configure stats pid to 36808
2023-12-03 18:33:32,732 INFO    MainThread:36808 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Josh\.config\wandb\settings
2023-12-03 18:33:32,732 INFO    MainThread:36808 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Josh\Documents\laz_final_proj\wandb\settings
2023-12-03 18:33:32,732 INFO    MainThread:36808 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-03 18:33:32,733 INFO    MainThread:36808 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-03 18:33:32,733 INFO    MainThread:36808 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\Josh\Documents\laz_final_proj\wandb\run-20231203_183332-0hp17a52\logs\debug.log
2023-12-03 18:33:32,734 INFO    MainThread:36808 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\Josh\Documents\laz_final_proj\wandb\run-20231203_183332-0hp17a52\logs\debug-internal.log
2023-12-03 18:33:32,734 INFO    MainThread:36808 [wandb_init.py:init():547] calling init triggers
2023-12-03 18:33:32,734 INFO    MainThread:36808 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'learning_rate': 1e-05, 'batch_size': 64, 'epochs': 30, 'weight_decay': 1e-05}
2023-12-03 18:33:32,734 INFO    MainThread:36808 [wandb_init.py:init():571] re-initializing run, found existing run on stack: gyon5c0q
2023-12-03 18:33:32,736 INFO    MainThread:36808 [wandb_run.py:_finish():1892] finishing run joshl/vision-project-resnet/gyon5c0q
2023-12-03 18:33:32,736 INFO    MainThread:36808 [jupyter.py:save_history():445] not saving jupyter history
2023-12-03 18:33:32,736 INFO    MainThread:36808 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-12-03 18:33:32,737 INFO    MainThread:36808 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2023-12-03 18:33:32,737 INFO    MainThread:36808 [wandb_run.py:_atexit_cleanup():2126] got exitcode: 0
2023-12-03 18:33:32,737 INFO    MainThread:36808 [wandb_run.py:_restore():2109] restore
2023-12-03 18:33:32,737 INFO    MainThread:36808 [wandb_run.py:_restore():2115] restore done
2023-12-03 18:33:36,369 INFO    MainThread:36808 [wandb_run.py:_footer_history_summary_info():3476] rendering history
2023-12-03 18:33:36,369 INFO    MainThread:36808 [wandb_run.py:_footer_history_summary_info():3508] rendering summary
2023-12-03 18:33:36,375 INFO    MainThread:36808 [wandb_run.py:_footer_sync_info():3434] logging synced files
2023-12-03 18:33:36,440 INFO    MainThread:36808 [wandb_init.py:init():595] starting backend
2023-12-03 18:33:36,440 INFO    MainThread:36808 [wandb_init.py:init():599] setting up manager
2023-12-03 18:33:36,443 INFO    MainThread:36808 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2023-12-03 18:33:36,446 INFO    MainThread:36808 [wandb_init.py:init():605] backend started and connected
2023-12-03 18:33:36,452 INFO    MainThread:36808 [wandb_run.py:_label_probe_notebook():1237] probe notebook
2023-12-03 18:33:36,452 INFO    MainThread:36808 [wandb_run.py:_label_probe_notebook():1247] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-12-03 18:33:36,452 INFO    MainThread:36808 [wandb_init.py:init():695] updated telemetry
2023-12-03 18:33:36,508 INFO    MainThread:36808 [wandb_init.py:init():732] communicating run to backend with 60.0 second timeout
2023-12-03 18:33:37,824 INFO    MainThread:36808 [wandb_run.py:_on_init():2176] communicating current version
2023-12-03 18:33:37,902 INFO    MainThread:36808 [wandb_run.py:_on_init():2185] got version response upgrade_message: "wandb version 0.16.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-12-03 18:33:37,902 INFO    MainThread:36808 [wandb_init.py:init():782] starting run threads in backend
2023-12-03 18:33:45,910 INFO    MainThread:36808 [wandb_run.py:_console_start():2157] atexit reg
2023-12-03 18:33:45,910 INFO    MainThread:36808 [wandb_run.py:_redirect():2012] redirect: SettingsConsole.WRAP_RAW
2023-12-03 18:33:45,910 INFO    MainThread:36808 [wandb_run.py:_redirect():2077] Wrapping output streams.
2023-12-03 18:33:45,910 INFO    MainThread:36808 [wandb_run.py:_redirect():2102] Redirects installed.
2023-12-03 18:33:45,911 INFO    MainThread:36808 [wandb_init.py:init():824] run started, returning control to user process
2023-12-03 18:58:36,394 INFO    MainThread:36808 [wandb_setup.py:_flush():76] Configure stats pid to 36808
2023-12-03 18:58:36,395 INFO    MainThread:36808 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Josh\.config\wandb\settings
2023-12-03 18:58:36,395 INFO    MainThread:36808 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Josh\Documents\laz_final_proj\wandb\settings
2023-12-03 18:58:36,396 INFO    MainThread:36808 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-12-03 18:58:36,396 INFO    MainThread:36808 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-03 18:58:36,397 INFO    MainThread:36808 [wandb_init.py:_log_setup():507] Logging user logs to C:\Users\Josh\Documents\laz_final_proj\wandb\run-20231203_185836-lrd3rhu2\logs\debug.log
2023-12-03 18:58:36,397 INFO    MainThread:36808 [wandb_init.py:_log_setup():508] Logging internal logs to C:\Users\Josh\Documents\laz_final_proj\wandb\run-20231203_185836-lrd3rhu2\logs\debug-internal.log
2023-12-03 18:58:36,398 INFO    MainThread:36808 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002386D260AF0>
2023-12-03 18:58:36,398 INFO    MainThread:36808 [wandb_init.py:init():547] calling init triggers
2023-12-03 18:58:36,398 INFO    MainThread:36808 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {'learning_rate': 1e-05, 'batch_size': 64, 'epochs': 50, 'weight_decay': 1e-05}
2023-12-03 18:58:36,398 INFO    MainThread:36808 [wandb_init.py:init():571] re-initializing run, found existing run on stack: 0hp17a52
2023-12-03 18:58:36,400 INFO    MainThread:36808 [wandb_run.py:_finish():1892] finishing run joshl/vision-project-resnet/0hp17a52
2023-12-03 18:58:36,401 INFO    MainThread:36808 [wandb_run.py:_atexit_cleanup():2126] got exitcode: 0
2023-12-03 18:58:36,401 INFO    MainThread:36808 [wandb_run.py:_restore():2109] restore
2023-12-03 18:58:36,401 INFO    MainThread:36808 [wandb_run.py:_restore():2115] restore done
2023-12-03 18:58:40,829 INFO    MainThread:36808 [wandb_run.py:_footer_history_summary_info():3476] rendering history
2023-12-03 18:58:40,830 INFO    MainThread:36808 [wandb_run.py:_footer_history_summary_info():3508] rendering summary
2023-12-03 18:58:40,835 INFO    MainThread:36808 [wandb_run.py:_footer_sync_info():3434] logging synced files
